### ISSUE TITLE
Crash on android release mode

### ISSUE THREAD

**Issue by bkoznov** [JideGuru/epub_viewer#105]
Issue / Feature -
Platform (android, iOS or both) - android in release mode 
Crash / Error - Crash

Steps to reproduce / Describe in detail - Opening an epub on the release build of an android app causes the app to crash 

Stack trace:

```FATAL EXCEPTION: main
E/AndroidRuntime(22922): Process: com.xyz.example, PID: 22922
E/AndroidRuntime(22922): gh.e: Subscriber class d3.b and its super classes have no public methods with the @Subscribe annotation
E/AndroidRuntime(22922):        at gh.p.a(Unknown Source:58)
E/AndroidRuntime(22922):        at gh.c.o(Unknown Source:6)
E/AndroidRuntime(22922):        at d3.b.w0(Unknown Source:34)
E/AndroidRuntime(22922):        at androidx.fragment.app.Fragment.Z0(Unknown Source:15)
E/AndroidRuntime(22922):        at androidx.fragment.app.j.U0(Unknown Source:645)
E/AndroidRuntime(22922):        at androidx.fragment.app.j.R0(Unknown Source:93)
E/AndroidRuntime(22922):        at androidx.fragment.app.j.S0(Unknown Source:42)
E/AndroidRuntime(22922):        at androidx.fragment.app.a.s(Unknown Source:173)
E/AndroidRuntime(22922):        at androidx.fragment.app.j.q0(Unknown Source:38)
E/AndroidRuntime(22922):        at androidx.fragment.app.j.r0(Unknown Source:113)
E/AndroidRuntime(22922):        at androidx.fragment.app.j.b1(Unknown Source:88)
E/AndroidRuntime(22922):        at androidx.fragment.app.j.p0(Unknown Source:31)
E/AndroidRuntime(22922):        at androidx.fragment.app.a.h(Unknown Source:6)
E/AndroidRuntime(22922):        at androidx.fragment.app.n.c(Unknown Source:4)
E/AndroidRuntime(22922):        at com.folioreader.ui.view.DirectionalViewpager.L(Unknown Source:649)
E/AndroidRuntime(22922):        at com.folioreader.ui.view.DirectionalViewpager.K(Unknown Source:2)
E/AndroidRuntime(22922):        at com.folioreader.ui.view.DirectionalViewpager.onMeasure(Unknown Source:248)
E/AndroidRuntime(22922):        at android.view.View.measure(View.java:25466)
E/AndroidRuntime(22922):        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(Unknown Source:500)
E/AndroidRuntime(22922):        at android.view.View.measure(View.java:25466)
E/AndroidRuntime(22922):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
E/AndroidRuntime(22922):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(22922):        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(Unknown Source:154)
E/AndroidRuntime(22922):        at android.view.View.measure(View.java:25466)
E/AndroidRuntime(22922):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
E/AndroidRuntime(22922):        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
E/AndroidRuntime(22922):        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
E/AndroidRuntime(22922):        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
E/AndroidRuntime(22922):        at android.view.View.measure(View.java:25466)
E/AndroidRuntime(22922):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
E/AndroidRuntime(22922):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(22922):        at android.view.View.measure(View.java:25466)
E/AndroidRuntime(22922):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
E/AndroidRuntime(22922):        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
E/AndroidRuntime(22922):        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
E/AndroidRuntime(22922):        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
E/AndroidRuntime(22922):        at android.view.View.measure(View.java:25466)
E/AndroidRuntime(22922):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6957)
E/AndroidRuntime(22922):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(22922):        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:747)
E/AndroidRuntime(22922):        at android.view.View.measure(View.java:25466)
E/AndroidRuntime(22922):        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3402)
E/AndroidRuntime(22922):        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2246)
E/AndroidRuntime(22922):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2504)
E/AndroidRuntime(22922):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1948)
E/AndroidRuntime(22922):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8177)
E/AndroidRuntime(22922):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
E/AndroidRuntime(22922):        at android.view.Choreographer.doCallbacks(Choreographer.java:796)
E/AndroidRuntime(22922):        at android.view.Choreographer.doFrame(Choreographer.java:731)
E/AndroidRuntime(22922):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
E/AndroidRuntime(22922):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(22922):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(22922):        at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(22922):        at android.app.ActivityThread.main(ActivityThread.java:7660)
E/AndroidRuntime(22922):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22922):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(22922):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)```

**Comment by bkoznov** [comment]
Sorry, fixed by https://github.com/JideGuru/epub_viewer/issues/48
