### ISSUE TITLE
App Crash When click On Pub Viewer (Android)

### ISSUE THREAD

**Issue by sagarshende23** [JideGuru/epub_viewer#121]
Issue / Feature - Issue
Platform (android, iOS or both) - Android
Crash / Error - Crash 

Steps to reproduce / Describe in detail - 
App Getting Crash if I Click on Epub Viewer, I am downloading file From Internet and then setting a android path. **When I try to open the file then app is Crashing**.. Epub Viewer Working fine For IOS

**Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added**

Following is the result I am getting in Debug Console..

W/Java7Support(25946): Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
I/Timeline(25946): Timeline: Activity_launch_request time:726193282
D/libMEOW (25946):   plugin 1: [libMEOW_gift.so]:
V/FolioActivity(25946): -> initDistractionFreeMode
D/DecorView[](25946): getWindowModeFromSystem  windowmode is 1
D/DecorView(25946): createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true
V/FolioActivity(25946): -> hideSystemUI
V/FolioActivity(25946): -> showSystemUI
W/om.dev.rachnay(25946): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/om.dev.rachnay(25946): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
V/FolioActivity(25946): -> setNightMode
V/FolioActivity(25946): -> initMediaController
V/FolioActivity(25946): -> setupBook
V/FolioActivity(25946): -> initBook
D/AppUtil (25946): -> getAvailablePortNumber -> portNumber 8080 available
V/FolioActivity(25946): -> onPostCreate
V/FolioActivity(25946): -> onResume
V/PhoneWindow(25946): DecorView setVisiblity: visibility = 4, Parent = null, this = DecorView@bd6ed57[]
D/ViewRootImpl[FolioActivity](25946): hardware acceleration = true , fakeHwAccelerated = false, sRendererDisabled = false, forceHwAccelerated = false, sSystemRendererDisabled = false
D/DecorView[](25946): getWindowModeFromSystem  windowmode is 1
I/InputTransport(25946): Create ARC handle: 0xb4000077fbadfd80
V/PhoneWindow(25946): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@3589cb0, this = DecorView@bd6ed57[FolioActivity]
W/Looper  (25946): PerfMonitor looperActivity : package=com.dev.rachnaye/com.folioreader.ui.activity.FolioActivity time=0ms latency=340ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=4 (msgIndex=4 wall=339ms seq=763 running=302ms runnable=1ms late=1ms h=android.app.ActivityThread$H w=159)
V/FolioAppBarLayout(25946): -> onApplyWindowInsets
I/TextToSpeech(25946): Sucessfully bound to com.google.android.tts
I/WebViewFactory(25946): Loading com.google.android.webview version 97.0.4692.87 (code 469208733)
W/om.dev.rachnay(25946): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
W/om.dev.rachnay(25946): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
W/om.dev.rachnay(25946): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
W/om.dev.rachnay(25946): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
W/om.dev.rachnay(25946): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
I/cr_WVCFactoryProvider(25946): Loaded version=97.0.4692.87 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
I/cr_LibraryLoader(25946): Successfully loaded native library
I/cr_CachingUmaRecorder(25946): Flushed 9 samples from 9 histograms.
I/TetheringManager(25946): registerTetheringEventCallback:com.dev.rachnaye
D/EgretLoader(25946): EgretLoader(Context context)
D/EgretLoader(25946): The context is not activity
V/FolioWebView(25946): -> init
V/FolioWebView(25946): -> initViewTextSelection
D/AndroidRuntime(25946): Shutting down VM
E/AndroidRuntime(25946): FATAL EXCEPTION: main
E/AndroidRuntime(25946): Process: com.dev.rachnaye, PID: 25946
E/AndroidRuntime(25946): java.lang.NoSuchFieldError: No static field abc_text_select_handle_middle_mtrl_dark of type I in class Lcom/folioreader/R$drawable; or its superclasses (declaration of 'com.folioreader.R$drawable' appears in /data/app/~~8EgezlZk1-329CPgraRODA==/com.dev.rachnaye-8vRIDc4BOW4ORKt8UmRE-g==/base.apk!classes2.dex)
E/AndroidRuntime(25946):        at com.folioreader.ui.view.FolioWebView.initViewTextSelection(FolioWebView.kt:287)
E/AndroidRuntime(25946):        at com.folioreader.ui.view.FolioWebView.init(FolioWebView.kt:279)
E/AndroidRuntime(25946):        at com.folioreader.ui.view.FolioWebView.setFolioActivityCallback(FolioWebView.kt:411)
E/AndroidRuntime(25946):        at com.folioreader.ui.fragment.FolioPageFragment.initWebView(FolioPageFragment.kt:375)
E/AndroidRuntime(25946):        at com.folioreader.ui.fragment.FolioPageFragment.onCreateView(FolioPageFragment.kt:183)
E/AndroidRuntime(25946):        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2963)
E/AndroidRuntime(25946):        at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:518)
E/AndroidRuntime(25946):        at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:282)
E/AndroidRuntime(25946):        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
E/AndroidRuntime(25946):        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
E/AndroidRuntime(25946):        at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
E/AndroidRuntime(25946):        at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
E/AndroidRuntime(25946):        at androidx.fragment.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:274)
E/AndroidRuntime(25946):        at com.folioreader.ui.view.DirectionalViewpager.populate(DirectionalViewpager.java:1327)
E/AndroidRuntime(25946):        at com.folioreader.ui.view.DirectionalViewpager.populate(DirectionalViewpager.java:1105)
E/AndroidRuntime(25946):        at com.folioreader.ui.view.DirectionalViewpager.onMeasure(DirectionalViewpager.java:1828)
E/AndroidRuntime(25946):        at android.view.View.measure(View.java:26026)
E/AndroidRuntime(25946):        at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
E/AndroidRuntime(25946):        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:632)
E/AndroidRuntime(25946):        at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:453)
E/AndroidRuntime(25946):        at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Direct.java:750)
E/AndroidRuntime(25946):        at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:505)
E/AndroidRuntime(25946):        at androidx.constraintlayout.core.widgets.analyzer.Direct.solvingPass(Direct.java:224)
E/AndroidRuntime(25946):        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:693)
E/AndroidRuntime(25946):        at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
E/AndroidRuntime(25946):        at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
E/AndroidRuntime(25946):        at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
E/AndroidRuntime(25946):        at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
E/AndroidRuntime(25946):        at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
E/AndroidRuntime(25946):        at android.view.View.measure(View.java:26026)
E/AndroidRuntime(25946):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
E/AndroidRuntime(25946):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(25946):        at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
E/AndroidRuntime(25946):        at android.view.View.measure(View.java:26026)
E/AndroidRuntime(25946):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
E/AndroidRuntime(25946):        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
E/AndroidRuntime(25946):        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
E/AndroidRuntime(25946):        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
E/AndroidRuntime(25946):        at android.view.View.measure(View.java:26026)
E/AndroidRuntime(25946):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
E/AndroidRuntime(25946):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(25946):        at android.view.View.measure(View.java:26026)
E/AndroidRuntime(25946):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
E/AndroidRuntime(25946):        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
E/AndroidRuntime(25946):        at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
E/AndroidRuntime(25946):        at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
E/AndroidRuntime(25946):        at android.view.View.measure(View.java:26026)
E/AndroidRuntime(25946):        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7105)
E/AndroidRuntime(25946):        at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
E/AndroidRuntime(25946):        at com.android.internal.policy.DecorView.onMeasure(DecorView.java:767)
E/AndroidRuntime(25946):        at android.view.View.measure(View.java:26026)
E/AndroidRuntime(25946):        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:3629)
E/AndroidRuntime(25946):        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2407)
E/AndroidRuntime(25946):        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2673)
E/AndroidRuntime(25946):        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2131)
E/AndroidRuntime(25946):        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8603)
E/AndroidRuntime(25946):        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:976)
E/AndroidRuntime(25946):        at android.view.Choreographer.doCallbacks(Choreographer.java:799)
E/AndroidRuntime(25946):        at android.view.Choreographer.doFrame(Choreographer.java:734)
E/AndroidRuntime(25946):        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:961)
E/AndroidRuntime(25946):        at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(25946):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25946):        at android.os.Looper.loop(Looper.java:236)
E/AndroidRuntime(25946):        at android.app.ActivityThread.main(ActivityThread.java:8031)
E/AndroidRuntime(25946):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25946):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:620)
E/AndroidRuntime(25946):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1011)
D/OOMEventManagerFK(25946): checkEventAndDumpForJE: 0
I/Process (25946): Sending signal. PID: 25946 SIG: 9
Lost connection to device.

**Comment by pradeep-kumar-rs** [comment]
Hello @sagarshende23 ,Did you get solution for this problem?

**Comment by sagarshende23** [comment]
Yeah..

**Comment by Tahaylmz** [comment]
Hello, I want to learn how to solved this problem.
