### ISSUE TITLE
App crash when trying to open the epub file

### ISSUE THREAD

**Issue by soleysok** [JideGuru/epub_viewer#29]
**Issue** - App crash when trying to open the epub file
**Platform** - Android

**Describe in detail** 
- **Below is my code and the errors**:
EpubViewer.setConfig(
        themeColor: Theme.of(context).primaryColor,
        identifier: "book",
        scrollDirection: EpubScrollDirection.VERTICAL,
        allowSharing: true,
        enableTts: true,
);
 note: it does not crash when I set the config but it crash when running the code below:
======= **Error Part**===========
EpubViewer.open(
        filePath,
);
==========================

- **This is the logs when the app crush:**
D/create table highlight( 3111): ****CREATE TABLE IF NOT EXISTS highlight_table ( _id INTEGER PRIMARY KEY AUTOINCREMENT,bookId TEXT,content TEXT,date TEXT,type TEXT,page_number INTEGER,pageId TEXT,rangy TEXT,uuid TEXT,note TEXT)
I/SavedLocation( 3111): -> savedLocation -> 
W/Java7Support( 3111): Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
W/ActivityThread( 3111): handleWindowVisibility: no activity for token android.os.BinderProxy@c25d30d
V/FolioActivity( 3111): -> initDistractionFreeMode
V/FolioActivity( 3111): -> hideSystemUI
V/FolioActivity( 3111): -> showSystemUI
W/le.camEducatio( 3111): Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
W/le.camEducatio( 3111): Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
V/FolioActivity( 3111): -> setDayMode
V/FolioActivity( 3111): -> initMediaController
V/FolioActivity( 3111): -> onPostCreate
V/FolioActivity( 3111): -> onResume
D/EGL_emulation( 3111): eglMakeCurrent: 0xdca53a40: ver 3 0 (tinfo 0xbd0cce10)
D/AndroidRuntime( 3111): Shutting down VM
E/AndroidRuntime( 3111): FATAL EXCEPTION: main
E/AndroidRuntime( 3111): Process: com.example.camEducation, PID: 3111
E/AndroidRuntime( 3111): android.view.InflateException: Couldn't resolve menu item onClick handler goBackButtonClicked in class com.folioreader.ui.activity.FolioActivity
E/AndroidRuntime( 3111):        at androidx.appcompat.view.SupportMenuInflater$InflatedOnMenuItemClickListener.<init>(SupportMenuInflater.java:255)
E/AndroidRuntime( 3111):        at androidx.appcompat.view.SupportMenuInflater$MenuState.setItem(SupportMenuInflater.java:484)
E/AndroidRuntime( 3111):        at androidx.appcompat.view.SupportMenuInflater$MenuState.addItem(SupportMenuInflater.java:532)
E/AndroidRuntime( 3111):        at androidx.appcompat.view.SupportMenuInflater.parseMenu(SupportMenuInflater.java:207)
E/AndroidRuntime( 3111):        at androidx.appcompat.view.SupportMenuInflater.inflate(SupportMenuInflater.java:129)
E/AndroidRuntime( 3111):        at com.folioreader.ui.activity.FolioActivity.onCreateOptionsMenu(FolioActivity.kt:398)
E/AndroidRuntime( 3111):        at android.app.Activity.onCreatePanelMenu(Activity.java:4074)
E/AndroidRuntime( 3111):        at androidx.fragment.app.FragmentActivity.onCreatePanelMenu(FragmentActivity.java:325)
E/AndroidRuntime( 3111):        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
E/AndroidRuntime( 3111):        at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:2830)
E/AndroidRuntime( 3111):        at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:94)
E/AndroidRuntime( 3111):        at androidx.appcompat.app.ToolbarActionBar.populateOptionsMenu(ToolbarActionBar.java:455)
E/AndroidRuntime( 3111):        at androidx.appcompat.app.ToolbarActionBar$1.run(ToolbarActionBar.java:56)
E/AndroidRuntime( 3111):        at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 3111):        at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 3111):        at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 3111):        at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime( 3111):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3111):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime( 3111):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime( 3111): Caused by: java.lang.NoSuchMethodException: com.folioreader.ui.activity.FolioActivity.goBackButtonClicked [interface android.view.MenuItem]
E/AndroidRuntime( 3111):        at java.lang.Class.getMethod(Class.java:2072)
E/AndroidRuntime( 3111):        at java.lang.Class.getMethod(Class.java:1693)
E/AndroidRuntime( 3111):        at androidx.appcompat.view.SupportMenuInflater$InflatedOnMenuItemClickListener.<init>(SupportMenuInflater.java:251)
E/AndroidRuntime( 3111):        ... 19 more

- **This pop up appear after the app crash:**
<img width="372" alt="Screen Shot 2020-09-29 at 11 50 31 AM" src="https://user-images.githubusercontent.com/45871758/94513939-282ff880-024a-11eb-91c6-e2bdcadf23ed.png">

**Comment by JideGuru** [comment]
Is this in Release mode, debug mode or both?

**Comment by soleysok** [comment]
I have only tested in dev and debug mode

**Comment by JideGuru** [comment]
Thanks @soleysok 
I'm looking into the issue

**Comment by JideGuru** [comment]
Is the epub file located in the device or assets?

**Comment by soleysok** [comment]
In the device.

**Comment by soleysok** [comment]
Plus, my problem is to deal with both pdf and epub, do you have any
suggestions for that?

**Comment by JideGuru** [comment]
There is no pdf support

**Comment by soleysok** [comment]
I see, anw I hope you can release another update soon.

**Comment by JideGuru** [comment]
@soleysok is it possible to share with me the file you used? and the android version?

**Comment by JideGuru** [comment]
@soleysok I published version 0.1.8 to fix your issue. can your use it and give me feedback?
Thanks

**Comment by soleysok** [comment]
yes thank you very much, it doesn't crash anymore, but all the functionalities are disappeared. Anyway, I am very thankful.
*Note: the android simulator devices that I use are:
    -Pixel 3 API 29(Android 10)
    -8 Foldable API 30(Android 11)
    -Nexus 5X API 24(Android 7)

**Comment by JideGuru** [comment]
@soleysok what do you mean by the functionality disappeared? can you share a screenshot?
and also you said you're using Emulators but the android emulator doesn't support running release mode.

**Comment by soleysok** [comment]
hello! sorry, I've been busy. As for the app, I am not yet done with all the feature yet so I haven't test it on release mode. Anyway, below is the screenshot of when I open the epub file.(there should be the setting for adjusting the brightness, font, scroll direction)
<img width="423" alt="Screen Shot 2020-10-05 at 9 11 47 AM" src="https://user-images.githubusercontent.com/45871758/95034304-7716db80-06eb-11eb-8a65-7286bcdad413.png">
