### ISSUE TITLE
Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added

### ISSUE THREAD

**Issue by chinkysight** [JideGuru/epub_viewer#98]
### Platform (android, iOS or both) :
 I am on **Android** only, so I don't know about **IOS**
### Error: 
```
I/SavedLocation(11367): -> savedLocation ->
W/System.err(11367): java.lang.NullPointerException: Attempt to read from field 'com.folioreader.Config com.jideguru.epub_viewer.ReaderConfig.config' on a null object reference
W/System.err(11367): 	at com.jideguru.epub_viewer.Reader$1.run(Reader.java:65)
W/System.err(11367): 	at java.lang.Thread.run(Thread.java:923)
W/Java7Support(11367): Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
```
### Describe in detail:

I have simply `TextButton` like this:

```
TextButton(
            onPressed: () async {
              await EpubViewer.openAsset('assets/4.epub');
            },
            child: Text('Clicke Me!'))
```
As you can see I am getting the `4.epub` from assets. But I wasn't able to do so. When I click the `TextButton`, following error is thrown without crashing the app:

```
I/SavedLocation(11367): -> savedLocation ->
W/System.err(11367): java.lang.NullPointerException: Attempt to read from field 'com.folioreader.Config com.jideguru.epub_viewer.ReaderConfig.config' on a null object reference
W/System.err(11367): 	at com.jideguru.epub_viewer.Reader$1.run(Reader.java:65)
W/System.err(11367): 	at java.lang.Thread.run(Thread.java:923)
W/Java7Support(11367): Unable to load JDK7 types (annotations, java.nio.file.Path): no Java7 support added
```

**Flutter Doctor Result:**
```
[√] Flutter (Channel stable, 2.2.0, on Microsoft Windows [Version 10.0.19043.1023], locale en-US)
    • Flutter version 2.2.0 at C:\fluttter\flutter
    • Framework revision b22742018b (2 weeks ago), 2021-05-14 19:12:57 -0700
    • Engine revision a9d88a4d18
    • Dart version 2.13.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\\\\Users\\\\Chinky Sight\\\\AppData\\\\Local\\\\Android\\\\Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Java\jdk1.8.0_291\bin\java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] VS Code (version 1.56.2)
    • VS Code at C:\Users\Chinky Sight\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (3 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 91.0.4472.77
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 91.0.864.37

! Doctor found issues in 1 category.
```

**Comment by NohchoBx** [comment]
Hi, any update on this?

**Comment by zatovagul** [comment]
+
